### PR TITLE
New iafd plugin

### PR DESCRIPTION
**Pull request by arcadianCdr**

### CODE REVIEW

**Comment by arcadianCdr** [comment]
Mmhhh failing test due to PromisedScene test case... so probably failing in master branch as well. I'll look into it a bit more later...

**Review by leadwolf — APPROVED** [review]
the readme isn't generated for some reason

**Comment by boi123212321** [comment]
Hmm not sure why md_gen isn't triggered on pull requests, it's set to trigger on all pushes

**Comment by boi123212321** [comment]
CI is failing because of linting, also, cheerio should now be imported by the plugin itself, as it's not part of the plugin context anymore

**Pull request closed without merging**
