### PR TITLE
Added career information scrape, and associated expected data for test.

### PR DESCRIPTION
**Pull request by johnnyporn88**

### CODE REVIEW

**Comment by leadwolf** [comment]
@johnnyporn88 Merge my PR, and this PR will be automatically updated https://github.com/johnnyporn88/porn-vault-plugins/pull/1 :)

**Comment by johnnyporn88** [comment]
@leadwolf your PR merged. But seems to result in conflict.

**Comment by leadwolf** [comment]
@johnnyporn88 Because some files were updated again at the same time in the main repo. Here's another merge https://github.com/johnnyporn88/porn-vault-plugins/pull/2

**Comment by leadwolf** [comment]
Replaced by #205, your commits are preserved

**Pull request closed without merging**
